create database`nashville housing`;
select * from `nashville housing`;
alter table `nashville housing` rename column ï»¿UniqueIDÂ to UniqueID;
alter table `nashville housing` drop column convert_date;
alter table `nashville housing` add column convert_date DATE;
select * from `nashville housing`;
update `nashville housing` set convert_date = STR_TO_DATE(SaleDate, '%m/%d/%Y');
select * from `nashville housing`;
select sum(TotalValue) from `nashville housing`;
select sum(BuildingValue) from `nashville housing`;
select * from `nashville housing` order by  OwnerAddress desc;
select distinct YearBuilt,OwnerAddress from `nashville housing`;
select distinct OwnerName,YearBuilt,OwnerAddress from `nashville housing`;
select OwnerName from `nashville housing` where OwnerName like '%O%';
select * from `nashville housing` where LandUse like '%duplex%';
select * from `nashville housing` where BuildingValue = (SELECT MAX(BuildingValue) FROM `nashville housing`);
select * from `nashville housing` where BuildingValue = (SELECT min(BuildingValue) FROM `nashville housing`);
select OwnerName from `nashville housing` where BuildingValue > 16000;
select * from `nashville housing` where LandUse = 'SINGLE FAMILY' and convert_date > 25000 and convert_date > '2019-10-10';
select OwnerName from `nashville housing` where LandValue > 28000 and BuildingValue > 70000 and YearBuilt > 1962;
